name: $(BuildDefinitionName)-$(Date:yyyyMMdd)$(Rev:.r)
pool: Hosted Ubuntu 1604
trigger:
- master
resources:
  repositories:
  - repository: templates
    type: git
    name: Glasswall.Pipelines.Templates
jobs:
- template: Python/template-ci.yml@templates
